"""otp challenges

Revision ID: 10715d761b0d
Revises: 8e436e0a5089
Create Date: 2026-07-15 00:50:01.368459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10715d761b0d'
down_revision: Union[str, Sequence[str], None] = '8e436e0a5089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otp_challenges')
    # ### end Alembic commands ###
