"""trusted devices

Revision ID: 40e0c0068fe0
Revises: 10715d761b0d
Create Date: 2026-07-15 01:46:40.438732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e0c0068fe0'
down_revision: Union[str, Sequence[str], None] = '10715d761b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('trusted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_account_device', 'trusted_devices', ['account_id', 'device_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_account_device', table_name='trusted_devices')
    op.drop_table('trusted_devices')
    # ### end Alembic commands ###
