"""enrich tenant

Revision ID: 6829781c47b1
Revises: c231ccfcfed0
Create Date: 2026-07-14 22:07:40.468624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6829781c47b1'
down_revision: Union[str, Sequence[str], None] = 'c231ccfcfed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False))
    op.add_column('tenants', sa.Column('denomination', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('estimated_member_count', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('country', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('city', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('address', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('tenants', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'longitude')
    op.drop_column('tenants', 'latitude')
    op.drop_column('tenants', 'address')
    op.drop_column('tenants', 'city')
    op.drop_column('tenants', 'country')
    op.drop_column('tenants', 'estimated_member_count')
    op.drop_column('tenants', 'contact_email')
    op.drop_column('tenants', 'denomination')
    op.drop_column('tenants', 'status')
    # ### end Alembic commands ###
