"""onboarding requests

Revision ID: 73e05c44d72a
Revises: 40e0c0068fe0
Create Date: 2026-07-15 09:59:01.037051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e05c44d72a'
down_revision: Union[str, Sequence[str], None] = '40e0c0068fe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('tenant_name', sa.String(), nullable=False),
    sa.Column('denomination', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('estimated_member_count', sa.Integer(), nullable=True),
    sa.Column('owner_email', sa.String(), nullable=False),
    sa.Column('owner_phone', sa.String(), nullable=False),
    sa.Column('owner_first_name', sa.String(), nullable=True),
    sa.Column('owner_last_name', sa.String(), nullable=True),
    sa.Column('owner_years_of_experience', sa.Integer(), nullable=True),
    sa.Column('owner_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarding_requests')
    # ### end Alembic commands ###
