"""urim corpus and preparation tables

Revision ID: a1b2c3d4e5f7
Revises: a7b8c9d0e1f2
Create Date: 2026-08-06 16:07:10.210591

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f7'
down_revision: str | Sequence[str] | None = 'a7b8c9d0e1f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urim_aggregate_signal_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('church_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('window_days', sa.SmallInteger(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('headcount >= 5', name='seuil_confidentialite'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_urim_aggregate_snapshot', 'urim_aggregate_signal_snapshot', ['church_id', 'fetched_at'], unique=False)
    op.create_table('urim_capture',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('church_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('preparation_id', sa.Uuid(), nullable=True),
    sa.Column('preached_on', sa.Date(), nullable=False),
    sa.Column('service_timezone', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model_ref', sa.String(), nullable=True),
    sa.Column('audio_purge_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('audio_purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('transcription_deferred', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('captée','transcrite','partielle','échouée')", name='capture_state'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_urim_capture_a_purger', 'urim_capture', ['audio_purge_at'], unique=False)
    op.create_index('ix_urim_capture_auteur', 'urim_capture', ['author_id', 'preached_on'], unique=False)
    op.create_table('urim_capture_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capture_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.CheckConstraint("kind IN ('transcrire','extraire_versets','aligner','purger_audio')", name='job_kind'),
    sa.CheckConstraint("state IN ('en_attente','en_cours','fait','echoue','abandonne')", name='job_state'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_urim_job_a_prendre', 'urim_capture_job', ['state', 'not_before'], unique=False)
    op.create_table('urim_cited_verse',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capture_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.SmallInteger(), nullable=False),
    sa.Column('chapter', sa.SmallInteger(), nullable=False),
    sa.Column('verse_start', sa.SmallInteger(), nullable=True),
    sa.Column('verse_end', sa.SmallInteger(), nullable=True),
    sa.Column('detected_by', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('segment_ordinal', sa.Integer(), nullable=False),
    sa.Column('was_prepared', sa.Boolean(), nullable=True),
    sa.CheckConstraint("detected_by IN ('enoncee','reconnue','fusionnee')", name='cited_verse_detected_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_urim_cited_verse_capture', 'urim_cited_verse', ['capture_id', 'segment_ordinal'], unique=False)
    op.create_index('ix_urim_cited_verse_passage', 'urim_cited_verse', ['book_id', 'chapter'], unique=False)
    op.create_table('urim_corpus_book',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('osis_code', sa.String(), nullable=False),
    sa.Column('testament', sa.String(), nullable=False),
    sa.Column('canon_order', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("testament IN ('AT','NT','DC')", name='book_testament'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osis_code')
    )
    op.create_table('urim_corpus_context_note',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pericope_id', sa.Uuid(), nullable=False),
    sa.Column('context_kind', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("context_kind IN ('historique','litteraire')", name='context_note_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pericope_id', 'context_kind', 'ordinal', name='context_note_ordre')
    )
    op.create_index('ix_urim_context_note_pericope', 'urim_corpus_context_note', ['pericope_id', 'ordinal'], unique=False)
    op.create_table('urim_corpus_doctrinal_axis',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('ordinal')
    )
    op.create_table('urim_corpus_idf',
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('idf', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('language', 'token')
    )
    op.create_table('urim_corpus_language',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('urim_corpus_lemma',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('lemma', sa.String(), nullable=False),
    sa.Column('strong_code', sa.String(), nullable=True),
    sa.Column('gloss', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urim_corpus_plan_source',
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('urim_corpus_subject_matter',
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('urim_corpus_versification_map',
    sa.Column('from_scheme', sa.String(), nullable=False),
    sa.Column('to_scheme', sa.String(), nullable=False),
    sa.Column('book_id', sa.SmallInteger(), nullable=False),
    sa.Column('from_ch', sa.SmallInteger(), nullable=False),
    sa.Column('from_v', sa.SmallInteger(), nullable=False),
    sa.Column('to_ch', sa.SmallInteger(), nullable=False),
    sa.Column('to_v', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('from_scheme', 'to_scheme', 'book_id', 'from_ch', 'from_v')
    )
    op.create_table('urim_ecclesial_event_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('church_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('occurs_on', sa.Date(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('WEDDING','BAPTISM','SPECIAL_SERVICE','WORSHIP_NIGHT','FAST','MEMORIAL_SERVICE','CONVENTION','EVANGELISM')", name='event_snapshot_liste_blanche'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_urim_event_snapshot', 'urim_ecclesial_event_snapshot', ['church_id', 'occurs_on'], unique=False)
    op.create_table('urim_preparation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('church_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('entry_mode', sa.String(), nullable=True),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('entry_origin', sa.String(), nullable=True),
    sa.Column('pericope_id', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Uuid(), nullable=True),
    sa.Column('axis_code', sa.String(), nullable=True),
    sa.Column('plan_source', sa.String(), nullable=True),
    sa.Column('subject_matter', sa.String(), nullable=True),
    sa.Column('override_start_ch', sa.SmallInteger(), nullable=True),
    sa.Column('override_start_v', sa.SmallInteger(), nullable=True),
    sa.Column('override_end_ch', sa.SmallInteger(), nullable=True),
    sa.Column('override_end_v', sa.SmallInteger(), nullable=True),
    sa.Column('theme', sa.Text(), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('service_timezone', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("entry_mode IN ('reference','citation','conviction')", name='prep_entry_mode'),
    sa.CheckConstraint("status IN ('ouverte','close','abandonnee')", name='prep_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_urim_prep_auteur', 'urim_preparation', ['author_id', 'opened_at'], unique=False)
    op.create_table('urim_reflection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capture_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('prepared_verses', sa.Integer(), nullable=False),
    sa.Column('cited_verses', sa.Integer(), nullable=False),
    sa.Column('unprepared', sa.Integer(), nullable=False),
    sa.Column('unspoken', sa.Integer(), nullable=False),
    sa.Column('synthesis', sa.JSON(), nullable=True),
    sa.Column('synthesis_state', sa.String(), nullable=True),
    sa.Column('validated_by', sa.Uuid(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("synthesis_state IN ('proposee','validee','rejetee')", name='reflection_state'),
    sa.CheckConstraint("synthesis_state IS DISTINCT FROM 'validee' OR (validated_by IS NOT NULL AND validated_at IS NOT NULL)", name='synthese_validee_signee'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capture_id')
    )
    op.create_table('urim_transcript_segment',
    sa.Column('capture_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('started_ms', sa.Integer(), nullable=False),
    sa.Column('ended_ms', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.CheckConstraint('ended_ms >= started_ms', name='segment_borne'),
    sa.PrimaryKeyConstraint('capture_id', 'ordinal')
    )
    op.create_table('urim_usage_window',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('church_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('metered_units', sa.Integer(), nullable=False),
    sa.Column('ceiling', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('church_id', 'period_start', name='usage_window_periode')
    )
    op.create_table('urim_corpus_book_name',
    sa.Column('book_id', sa.SmallInteger(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('abbreviations', sa.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['urim_corpus_book.id'], ),
    sa.ForeignKeyConstraint(['language'], ['urim_corpus_language.code'], ),
    sa.PrimaryKeyConstraint('book_id', 'language')
    )
    op.create_table('urim_corpus_pericope',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.SmallInteger(), nullable=False),
    sa.Column('start_ch', sa.SmallInteger(), nullable=False),
    sa.Column('start_v', sa.SmallInteger(), nullable=False),
    sa.Column('end_ch', sa.SmallInteger(), nullable=False),
    sa.Column('end_v', sa.SmallInteger(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['urim_corpus_book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_urim_pericope_book', 'urim_corpus_pericope', ['book_id', 'start_ch', 'start_v'], unique=False)
    op.create_table('urim_corpus_textual_variant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.SmallInteger(), nullable=False),
    sa.Column('chapter', sa.SmallInteger(), nullable=False),
    sa.Column('verse', sa.SmallInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('families_with', sa.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('families_without', sa.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('doctrinal_weight', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("doctrinal_weight IN ('nul','notable','majeur')", name='variant_weight'),
    sa.ForeignKeyConstraint(['book_id'], ['urim_corpus_book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_urim_variant_ref', 'urim_corpus_textual_variant', ['book_id', 'chapter', 'verse'], unique=False)
    op.create_table('urim_corpus_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('translation_kind', sa.String(), nullable=False),
    sa.Column('license_kind', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('offline_allowed', sa.Boolean(), nullable=False),
    sa.Column('metered', sa.Boolean(), nullable=False),
    sa.Column('versification', sa.String(), nullable=False),
    sa.CheckConstraint("(license_kind = 'domaine_public' AND offline_allowed AND NOT metered) OR license_kind = 'sous_licence'", name='licence_coherente'),
    sa.CheckConstraint("license_kind IN ('domaine_public','sous_licence')", name='version_license_kind'),
    sa.CheckConstraint("translation_kind IN ('formelle','dynamique','original')", name='version_translation_kind'),
    sa.ForeignKeyConstraint(['language'], ['urim_corpus_language.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('urim_deliverable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('preparation_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validation', sa.String(), nullable=True),
    sa.CheckConstraint("kind IN ('pptx','pdf')", name='deliverable_kind'),
    sa.CheckConstraint("validation IN ('conforme','rejete')", name='deliverable_validation'),
    sa.ForeignKeyConstraint(['preparation_id'], ['urim_preparation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urim_preached',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('preparation_id', sa.Uuid(), nullable=True),
    sa.Column('church_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('preached_on', sa.Date(), nullable=False),
    sa.Column('book_id', sa.SmallInteger(), nullable=True),
    sa.Column('start_ch', sa.SmallInteger(), nullable=True),
    sa.Column('start_v', sa.SmallInteger(), nullable=True),
    sa.Column('end_ch', sa.SmallInteger(), nullable=True),
    sa.Column('end_v', sa.SmallInteger(), nullable=True),
    sa.Column('axis_code', sa.String(), nullable=True),
    sa.Column('theme', sa.Text(), nullable=True),
    sa.Column('capture_kind', sa.String(), nullable=True),
    sa.Column('exportable_until', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("capture_kind IN ('dictee','saisie','import')", name='preached_capture_kind'),
    sa.ForeignKeyConstraint(['preparation_id'], ['urim_preparation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_urim_preached_axe', 'urim_preached', ['author_id', 'axis_code', 'preached_on'], unique=False)
    op.create_index('ix_urim_preached_passage', 'urim_preached', ['author_id', 'book_id', 'start_ch'], unique=False)
    op.create_table('urim_preparation_element',
    sa.Column('preparation_id', sa.Uuid(), nullable=False),
    sa.Column('element_code', sa.String(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['preparation_id'], ['urim_preparation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('preparation_id', 'element_code', 'ordinal')
    )
    op.create_table('urim_resolution_attempt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('preparation_id', sa.Uuid(), nullable=False),
    sa.Column('input_hash', sa.String(), nullable=False),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('chosen_ref', sa.String(), nullable=True),
    sa.Column('chosen_by', sa.String(), nullable=True),
    sa.Column('version_detected', sa.Uuid(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("chosen_by IN ('moteur','pasteur')", name='attempt_chosen_by'),
    sa.ForeignKeyConstraint(['preparation_id'], ['urim_preparation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_urim_attempt_prep', 'urim_resolution_attempt', ['preparation_id', 'attempted_at'], unique=False)
    op.create_table('urim_study_reservation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('church_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('pericope_key', sa.String(), nullable=False),
    sa.Column('window_id', sa.Uuid(), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['window_id'], ['urim_usage_window.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_urim_reservation_idempotente', 'urim_study_reservation', ['church_id', 'author_id', 'pericope_key'], unique=True, postgresql_where=sa.text('released_at IS NULL'), sqlite_where=sa.text('released_at IS NULL'))
    op.create_table('urim_citation_check',
    sa.Column('deliverable_id', sa.Uuid(), nullable=False),
    sa.Column('slide_no', sa.SmallInteger(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('projected_text', sa.Text(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.CheckConstraint("verdict IN ('exact','extrait','altere')", name='citation_verdict'),
    sa.ForeignKeyConstraint(['deliverable_id'], ['urim_deliverable.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deliverable_id', 'slide_no')
    )
    op.create_table('urim_corpus_doctrinal_bearing',
    sa.Column('pericope_id', sa.Uuid(), nullable=False),
    sa.Column('axis_code', sa.String(), nullable=False),
    sa.Column('strength', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("strength IN ('dominant','porte','resiste','absent')", name='bearing_strength'),
    sa.ForeignKeyConstraint(['axis_code'], ['urim_corpus_doctrinal_axis.code'], ),
    sa.ForeignKeyConstraint(['pericope_id'], ['urim_corpus_pericope.id'], ),
    sa.PrimaryKeyConstraint('pericope_id', 'axis_code')
    )
    op.create_table('urim_corpus_doctrinal_caveat',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pericope_id', sa.Uuid(), nullable=False),
    sa.Column('axis_code', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('caveat_kind', sa.String(), nullable=False),
    sa.Column('tradition_scope', sa.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("caveat_kind = 'exegetique' OR tradition_scope IS NOT NULL", name='confessionnel_borne'),
    sa.CheckConstraint("caveat_kind IN ('exegetique','confessionnel')", name='caveat_kind_clos'),
    sa.ForeignKeyConstraint(['axis_code'], ['urim_corpus_doctrinal_axis.code'], ),
    sa.ForeignKeyConstraint(['pericope_id'], ['urim_corpus_pericope.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_urim_caveat_pericope', 'urim_corpus_doctrinal_caveat', ['pericope_id', 'axis_code'], unique=False)
    op.create_table('urim_corpus_homiletic_feasibility',
    sa.Column('pericope_id', sa.Uuid(), nullable=False),
    sa.Column('plan_source', sa.String(), nullable=False),
    sa.Column('subject_matter', sa.String(), nullable=False),
    sa.Column('feasible', sa.Boolean(), nullable=False),
    sa.Column('refusal_reason', sa.Text(), nullable=True),
    sa.Column('proof_text_risk', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("proof_text_risk IN ('faible','moyen','eleve')", name='feasibility_risk'),
    sa.CheckConstraint('feasible OR refusal_reason IS NOT NULL', name='refus_motive'),
    sa.ForeignKeyConstraint(['pericope_id'], ['urim_corpus_pericope.id'], ),
    sa.ForeignKeyConstraint(['plan_source'], ['urim_corpus_plan_source.code'], ),
    sa.ForeignKeyConstraint(['subject_matter'], ['urim_corpus_subject_matter.code'], ),
    sa.PrimaryKeyConstraint('pericope_id', 'plan_source', 'subject_matter')
    )
    op.create_table('urim_corpus_verse',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.SmallInteger(), nullable=False),
    sa.Column('chapter', sa.SmallInteger(), nullable=False),
    sa.Column('verse', sa.SmallInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_norm', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['urim_corpus_book.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['urim_corpus_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'book_id', 'chapter', 'verse', name='verse_unique_ref')
    )
    op.create_index('ix_urim_verse_ref', 'urim_corpus_verse', ['version_id', 'book_id', 'chapter', 'verse'], unique=False)
    op.create_table('urim_corpus_token',
    sa.Column('verse_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('surface', sa.String(), nullable=False),
    sa.Column('lemma_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('morph_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lemma_id'], ['urim_corpus_lemma.id'], ),
    sa.ForeignKeyConstraint(['verse_id'], ['urim_corpus_verse.id'], ),
    sa.PrimaryKeyConstraint('verse_id', 'position')
    )
    # ### end Alembic commands ###

    _semer_le_vocabulaire()


#: Les dix **loci** de la théologie systématique, dans leur ordre traditionnel — qui est aussi
#: celui d'un plan de catéchèse. Des données, jamais un enum de code : l'écran trie par force ou
#: par ordre canonique sans le coder en dur.
_AXES = (
    ("theologie_propre", "Théologie propre — Dieu", 1),
    ("christologie", "Christologie — Jésus-Christ", 2),
    ("pneumatologie", "Pneumatologie — le Saint-Esprit", 3),
    ("anthropologie", "Anthropologie — l'homme", 4),
    ("hamartiologie", "Hamartiologie — le péché", 5),
    ("soteriologie", "Sotériologie — le salut", 6),
    ("ecclesiologie", "Ecclésiologie — l'Église", 7),
    ("angelologie", "Angélologie — les anges", 8),
    ("demonologie", "Démonologie — Satan et les démons", 9),
    ("eschatologie", "Eschatologie — les derniers temps", 10),
)

#: Les deux axes homilétiques, **orthogonaux** : d'où le plan tire sa structure, et de quoi il
#: traite. Leur croisement est ce que `urim_corpus_homiletic_feasibility` pèse péricope par
#: péricope — et refuse, quand il le faut, avec un motif signé.
_PLAN_SOURCES = ("textuel", "expositif", "thematique")
_SUBJECT_MATTERS = (
    "biographique", "doctrinal", "ethique", "historique", "typologique", "prophetique",
)


def _semer_le_vocabulaire() -> None:
    """Le vocabulaire **fermé** — et lui seul.

    Ces dix-neuf lignes ne sont pas de la curation : ce sont des codes de référence que la
    spécification fixe littéralement, et vers lesquels trois tables pointent par clé étrangère.
    Sans eux, aucune pesée doctrinale ni aucune faisabilité ne peut s'insérer.

    Ce qui **n'est pas** ici et n'y sera jamais : les péricopes, les pesées, les mises en garde,
    les notes de contexte, les faisabilités. Elles portent `reviewed_by NOT NULL`, et une
    migration ne signe pas à la place d'un relecteur.
    """
    op.bulk_insert(
        sa.table(
            "urim_corpus_doctrinal_axis",
            sa.column("code", sa.String),
            sa.column("label", sa.String),
            sa.column("ordinal", sa.SmallInteger),
        ),
        [{"code": c, "label": lab, "ordinal": o} for c, lab, o in _AXES],
    )
    op.bulk_insert(
        sa.table("urim_corpus_plan_source", sa.column("code", sa.String)),
        [{"code": code} for code in _PLAN_SOURCES],
    )
    op.bulk_insert(
        sa.table("urim_corpus_subject_matter", sa.column("code", sa.String)),
        [{"code": code} for code in _SUBJECT_MATTERS],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urim_corpus_token')
    op.drop_index('ix_urim_verse_ref', table_name='urim_corpus_verse')
    op.drop_table('urim_corpus_verse')
    op.drop_table('urim_corpus_homiletic_feasibility')
    op.drop_index('ix_urim_caveat_pericope', table_name='urim_corpus_doctrinal_caveat')
    op.drop_table('urim_corpus_doctrinal_caveat')
    op.drop_table('urim_corpus_doctrinal_bearing')
    op.drop_table('urim_citation_check')
    op.drop_index('ix_urim_reservation_idempotente', table_name='urim_study_reservation', postgresql_where=sa.text('released_at IS NULL'), sqlite_where=sa.text('released_at IS NULL'))
    op.drop_table('urim_study_reservation')
    op.drop_index('ix_urim_attempt_prep', table_name='urim_resolution_attempt')
    op.drop_table('urim_resolution_attempt')
    op.drop_table('urim_preparation_element')
    op.drop_index('ix_urim_preached_passage', table_name='urim_preached')
    op.drop_index('ix_urim_preached_axe', table_name='urim_preached')
    op.drop_table('urim_preached')
    op.drop_table('urim_deliverable')
    op.drop_table('urim_corpus_version')
    op.drop_index('ix_urim_variant_ref', table_name='urim_corpus_textual_variant')
    op.drop_table('urim_corpus_textual_variant')
    op.drop_index('ix_urim_pericope_book', table_name='urim_corpus_pericope')
    op.drop_table('urim_corpus_pericope')
    op.drop_table('urim_corpus_book_name')
    op.drop_table('urim_usage_window')
    op.drop_table('urim_transcript_segment')
    op.drop_table('urim_reflection')
    op.drop_index('ix_urim_prep_auteur', table_name='urim_preparation')
    op.drop_table('urim_preparation')
    op.drop_index('ix_urim_event_snapshot', table_name='urim_ecclesial_event_snapshot')
    op.drop_table('urim_ecclesial_event_snapshot')
    op.drop_table('urim_corpus_versification_map')
    op.drop_table('urim_corpus_subject_matter')
    op.drop_table('urim_corpus_plan_source')
    op.drop_table('urim_corpus_lemma')
    op.drop_table('urim_corpus_language')
    op.drop_table('urim_corpus_idf')
    op.drop_table('urim_corpus_doctrinal_axis')
    op.drop_index('ix_urim_context_note_pericope', table_name='urim_corpus_context_note')
    op.drop_table('urim_corpus_context_note')
    op.drop_table('urim_corpus_book')
    op.drop_index('ix_urim_cited_verse_passage', table_name='urim_cited_verse')
    op.drop_index('ix_urim_cited_verse_capture', table_name='urim_cited_verse')
    op.drop_table('urim_cited_verse')
    op.drop_index('ix_urim_job_a_prendre', table_name='urim_capture_job')
    op.drop_table('urim_capture_job')
    op.drop_index('ix_urim_capture_auteur', table_name='urim_capture')
    op.drop_index('ix_urim_capture_a_purger', table_name='urim_capture')
    op.drop_table('urim_capture')
    op.drop_index('ix_urim_aggregate_snapshot', table_name='urim_aggregate_signal_snapshot')
    op.drop_table('urim_aggregate_signal_snapshot')
    # ### end Alembic commands ###
